#!/usr/bin/perl

use strict;
use esmith::Build::CreateLinks  qw(:all);

#--------------------------------------------------
# actions for nethserver-postgresql-update event
#--------------------------------------------------

my $event = "nethserver-postal-update";

event_actions($event, 
    'initialize-default-databases' => '00',
    'nethserver-postal-conf' => '01' 
);

event_templates($event, 
    '/etc/httpd/conf.d/postal.conf',
    '/opt/postal/config/postal.yml'
);

event_services($event, 
    'httpd' => 'restart',
    'postal' => 'restart'
);

#--------------------------------------------------
# actions for pre-backup-data event
#--------------------------------------------------

$event = 'pre-backup-data';

event_actions($event, 'nethserver-postal-backup' => 50);

#--------------------------------------------------
# actions for post-restore-data event
#--------------------------------------------------

$event = 'post-restore-data';

event_actions($event, 'nethserver-postal-restore' => 50);

event_services($event, 'postal' => 'restart');
