#!/bin/bash

# Initialize postal
postal initialize

# start postal
postal start

# Make-use needs to be done manually
#postal make-user
#wait

# Create start script and cronize it - replace with systemd when possible
echo "#!/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
LD_LIBRARY_PATH=/usr/local/lib
/usr/bin/postal status | grep Exit && date >> ~/logpostal.log
/usr/bin/postal status | grep Exit && /usr/bin/postal start" > ~/postalCheck.sh

chmod +x ~/postalCheck.sh

echo "@reboot sleep 60 && ~/postalCheck.sh" >> /etc/crontab
