#!/bin/bash

# docker compose
curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

# get installation
git clone https://postalserver.io/start/install /opt/postal/install
ln -s /opt/postal/install/bin/postal /usr/bin/postal

#head /dev/urandom | tr -dc A-Za-z0-9 | head -c10 >> ~/pass.txt
password=`perl -e "use NethServer::Password; print NethServer::Password::store('postal');"`

# Run rabbitmq container
docker run -d \
   --name postal-rabbitmq \
   -p 127.0.0.1:5672:5672 \
   --restart always \
   -e RABBITMQ_DEFAULT_USER=postal \
   -e RABBITMQ_DEFAULT_PASS=$password \
   -e RABBITMQ_DEFAULT_VHOST=postal \
   rabbitmq:3.8
wait

# Run mariadb container
docker run -d \
   --name postal-mariadb \
   -p 127.0.0.1:3307:3306 \
   --restart always \
   -e MARIADB_DATABASE=postal \
   -e MARIADB_ROOT_PASSWORD=$password \
   mariadb
wait

#Use custom virtualhost name or Nethserver domain name

domain=`config getprop postal VirtualHost`
if [[ $domain = '' ]]; then domain=`config get DomainName`; fi

# Bootstrap Postal - maybe only do it once?
postal bootstrap postal.$domain
wait

# Edit postal.yml

sed -i '3s/  use_ip_pools: .*/  use_ip_pools: true/' /opt/postal/config/postal.yml;
sed -i '13s/  bind_address: .*/  bind_address: 172.17.0.1/' /opt/postal/config/postal.yml;
sed -i '18s/  port: .*/  port: 465/' /opt/postal/config/postal.yml;
sed -i "41s/host: .*/host: $(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' `docker ps -aqf "name=postal-rabbitmq"`)/g" /opt/postal/config/postal.yml;
sed -i "26s/host: .*/host: $(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' `docker ps -aqf "name=postal-mariadb"`)/g" /opt/postal/config/postal.yml;
sed -i '52s/smtp_server_hostname: .*/smtp_server_hostname: '"postal.$domain"'/g' /opt/postal/config/postal.yml;
sed -i "34s/host: .*/host: $(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' `docker ps -aqf "name=postal-mariadb"`)/g" /opt/postal/config/postal.yml;
sed -i '56s/track_domain: .*/track_domain: '"track.postal.$domain"'/g' /opt/postal/config/postal.yml;
sed -i '55s/route_domain: .*/route_domain: '"routes.postal.$domain"'/g' /opt/postal/config/postal.yml;
sed -i '54s/return_path: .*/return_path: '"return.postal.$domain"'/g' /opt/postal/config/postal.yml;
sed -i '53s/spf_include: .*/spf_include: '"spf.postal.$domain"'/g' /opt/postal/config/postal.yml;
sed -i '51s/  - .*/  - '"postal.$domain"'/g' /opt/postal/config/postal.yml;
sed -i "43s/password: .*/password: $password/g" /opt/postal/config/postal.yml;
sed -i "28s/password: .*/password: $password/g" /opt/postal/config/postal.yml;
sed -i "36s/password: .*/password: $password/g" /opt/postal/config/postal.yml;
