#!/bin/bash

input=$(cat)
action=$(jq -r .action <<<"$input")

if [[ $action == "app-info" ]]; then
    if [[ $(/sbin/e-smith/config getprop postal status) == "enabled" ]]; then
        vhost=postal.$(/sbin/e-smith/config getprop postal VirtualHost)
        if [[ $vhost = 'postal.' ]]; then vhost=postal.$(/sbin/e-smith/config get DomainName); fi
        printf '{"url":"%s"}' "https://${vhost}"
    else
        printf '{}'
    fi
fi
